change all getters to functions on netPlayer
the problem with getters is it breaks shit. If there was code like

   netPlayer.name = foo

then suddenly adding a setter breaks it

   ERROR: trying to set property with no setter